dbt_project:
  outputs:
    dev:
      dataset: staging
      job_execution_timeout_seconds: 250
      job_retries: 1
      keyfile: /credentials/google_credentials.json
      location: EU
      method: service-account
      priority: interactive
      project: dtc-trips
      threads: 4
      type: bigquery
  target: dev
